
{{- if .Values.webapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}
spec:
  rules:
    - host: {{ .Values.webapp.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webapp.name }}
                port:
                  number: {{ .Values.webapp.port }}
{{- end }}
