apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.webapp.name } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { .Values.webapp.name } }
  template:
    metadata:
      labels:
        app: { { .Values.webapp.name } }
    spec:
      containers:
        - name: { { .Values.webapp.name } }
          image: { { .Values.webapp.image } }
          ports:
            - containerPort: { { .Values.webapp.port } }
