apiVersion: v1
kind: Service
metadata:
  name: { { .Values.webapp.name } }
spec:
  selector:
    app: { { .Values.webapp.name } }
  ports:
    - port: { { .Values.webapp.port } }
      targetPort: { { .Values.webapp.port } }
  type: ClusterIP
