name: Package and Release Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Package charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            helm package "$chart" --destination ./packaged
          done

      - name: Generate Helm repo index
        run: |
          mkdir -p docs
          cp -r packaged/* docs/
          helm repo index docs --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Commit and push to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Update chart packages and index [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Create GitHub release for each chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for chart in packaged/*.tgz; do
            chart_name=$(basename "$chart" .tgz)
            version=$(echo "$chart_name" | awk -F- '{print $NF}')
            name=$(echo "$chart_name" | sed "s/-$version//")
            gh release create "$name-v$version" "$chart" \
              --repo "$GITHUB_REPOSITORY" \
              --title "$name v$version" \
              --notes "Release of $name chart version $version" || echo "Release already exists"
          done
